### ISSUE TITLE
Cant change port

### ISSUE THREAD

**Issue by Yakrel** [natankeddem/bale#3]
Hi, I did change port to 8181 but looks like bale still running on 8080,

Here is my docker compose file

```
networks:
  infrastructure:
    name: infrastructure
    external: true

services:
  bale:
    image: ghcr.io/natankeddem/bale:latest
    container_name: bale
    ports:
      - 8181:8181
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BALE_CONFIG}:/app/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERBOSE_LOGGING=TRUE
    networks:
      - infrastructure
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "2"
```
        

and here my logs

```
docker logs bale 
+ PUID=1000
+ PGID=1000
+ [[ 1000 =~ ^[0-9]+$ ]]
+ [[ 1000 =~ ^[0-9]+$ ]]
+ getent group 1000
+ groupadd -g 1000 appgroup
+ useradd --create-home --shell /bin/bash --uid 1000 --gid 1000 appuser
+ mkdir -p /app/mpl
+ chown -R appuser:appgroup /app
+ mkdir -p /home/appuser/.ssh
+ chown appuser:appgroup /home/appuser/.ssh
+ cp /etc/skel/.bashrc /home/appuser/.bashrc
+ chown appuser:appgroup /home/appuser/.bashrc
+ export HOME=/home/appuser
+ HOME=/home/appuser
+ '[' -d /usr/share/fonts ']'
+ chmod -R 777 /usr/share/fonts
+ '[' -d /var/cache/fontconfig ']'
+ chmod -R 777 /var/cache/fontconfig
+ '[' -d /usr/local/share/fonts ']'
+ chmod -R 777 /usr/local/share/fonts
+ exec setpriv --reuid=1000 --regid=1000 --init-groups python main.py
2024-10-23 08:29:36,680-WARNING-mylogging-1::mylogging|115:: ***Verbose Logging Started***
2024-10-23 08:29:36,680-WARNING-__main__-1::main|8:: Could not find 'data' directory, verify bind mounts.
2024-10-23 08:29:36,681-WARNING-__main__-1::main|13:: Creating 'data' directory, settings will not be persistent.
Starting bale, bound to the following addresses http://172.18.0.6:8080, http://localhost:8080.
```

**Comment by natankeddem** [comment]
Hi @Yakrel,
The internal port bale runs on is static and doesn't have any mechanism to change currently. Although that shouldn't be necessary. I think you can change `ports` to `8181:8080` to accomplish what you want. See the following for reference: 
https://docs.docker.com/get-started/docker-concepts/running-containers/publishing-ports/

**Comment by Yakrel** [comment]
Sadly I need internal port to be changed too.

**Comment by natankeddem** [comment]
Hi @Yakrel ,
Can you describe your use case for this change? I am curious why you can't use the docker port remapping.

**Comment by Yakrel** [comment]
I have another app that using the ports and it is same as bale when I change port, it doesnt apply it, so I cant use both apps in same WM.

**Comment by natankeddem** [comment]
Are you utilizing docker or running bale in another configuration?

**Comment by Yakrel** [comment]
I am using both bale and other app via compose file so I am using docker.

**Comment by natankeddem** [comment]
Unless you can provide me a reason why you can't use the built in port remapping in Docker, I am hesitant to make any changes. This is a solved problem with Docker, we shouldn't be trying to reinvent the wheel. I can easily run multiple instances of bale in docker concurrently on different ports on the same host, you should be able to do the same with other applications:

```
version: "3.8"

services:
  balex:
    image: ghcr.io/natankeddem/bale:latest
    ports:
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/path/to/data/baledatax:/app/data
      - ~/path/to/data/balelogsx:/app/logs
    environment:
      - PUID=1000
      - PGID=1000
      - VERBOSE_LOGGING=TRUE # Optional
  baley:
    image: ghcr.io/natankeddem/bale:latest
    ports:
      - 8181:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/path/to/data/baledatay:/app/data
      - ~/path/to/data/balelogsy:/app/logs
    environment:
      - PUID=1000
      - PGID=1000
      - VERBOSE_LOGGING=TRUE # Optional
```
